USER-SUPPLIED VALUES:
git:
  branch: main
  email: keel-bot@example.com
  repo: https://github.com/RavidShlomian/Comm-IT-Assignment.git
  tokenSecret: github-token-secret
  username: github-actions
docker:
  repos:
    - 324483885455.dkr.ecr.eu-north-1.amazonaws.com/nginx-service  # ECR repository for your service
  username: AWS  # For ECR, set the username as 'AWS' for IAM authentication

env:
  - name: AWS_REGION
    value: eu-north-1 
ecr:
  enabled: true
  region: eu-north-1
serviceAccountName:
  create: false  # Set to false if you are using an existing service account
  name: keel-service-account 
service:
  type: LoadBalancer
  port: 80
  targetPort: 80